package com.autazcloud.pdv.domain.enums;

public enum ActionsEnum {
	ACTION_VIDEO_MINIMIZE, ACTION_VIDEO_MAXIMIZE, ACTION_POWER_CONNECTED, ACTION_POWER_DISCONNECTED, STARTED_DEVICE, STARTED_APPLICATION, LOW_BATTERY;
}
